apiVersion: apps/v1
kind: Deployment
metadata:
  name: workhub-app-green
  namespace: workhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workhub-app
      version: green
  template:
    metadata:
      labels:
        app: workhub-app
        version: green
    spec:
      containers:
        - name: workhub-app
          image: workhub-app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: workhub-config
            - secretRef:
                name: workhub-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"