apiVersion: v1
kind: Secret
metadata:
  name: workhub-secret
  namespace: workhub
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "workhub_user"
  SPRING_DATASOURCE_PASSWORD: "workhub_pass"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
  JWT_SECRET: "workhub-super-secret-key-must-be-at-least-256-bits-long-here"